# Generated by Django 3.1.1 on 2020-11-02 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_remove_orderlineitem_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='non_delivery',
            field=models.DecimalField(
                                      decimal_places=2,
                                      default=0,
                                      max_digits=10),
        ),
    ]
